version: "3"
services:
  express-server:
    container_name: express-server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"